Repository jrj-sys/PokeHunt, pull requests merged in 2022-03, with the labels that each got.

#7 update README.md
  README.md
Labels: enhancement

#8 initial project files, add '.DS_Store' to .gitignore for MacOS
  .gitignore
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#26 Bug fix: toLowerCase user input for API search criteria
  assets/js/script.js
Labels: bug

#29 Feature/recently searched
  assets/js/script.js
  index.html
Labels: enhancement

#30 MVP merge
  .gitignore
  README.md
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#34 Feature/capital punctuation
  assets/js/script.js
Labels: edit

#36 force merge for sake of time
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: edit

#38 added footer!
  assets/css/style.css
  index.html
Labels: enhancement
